# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudsql < Formula
  desc "cloudsql"
  homepage "https://github.com/s-okayama/cloudsql"
  version "2.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s-okayama/cloudsql/releases/download/v2.1.2/cloudsql_2.1.2_Darwin_64bit.tar.gz"
      sha256 "444c1c805051af5ca8430a0f89235909f4400eae568ed591bf2e488625372f5d"

      def install
        bin.install "cloudsql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s-okayama/cloudsql/releases/download/v2.1.2/cloudsql_2.1.2_Darwin_ARM64.tar.gz"
      sha256 "d766a7edf3a0ee55ff352d658e298f9468b5fc1a8ef87571b9585b99ca094bd6"

      def install
        bin.install "cloudsql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/s-okayama/cloudsql/releases/download/v2.1.2/cloudsql_2.1.2_Linux_64bit.tar.gz"
      sha256 "9356eabc397abd9bbd56270261041f5024c901617e88d350ae7779389587dd0b"
      def install
        bin.install "cloudsql"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/s-okayama/cloudsql/releases/download/v2.1.2/cloudsql_2.1.2_Linux_ARM64.tar.gz"
      sha256 "32b33dc4d95ec656c7409ac7e6ac5615d604e58f9482ace7bf26a3cd9152810a"
      def install
        bin.install "cloudsql"
      end
    end
  end

  test do
    system "#{bin}/cloudsql --version"
  end
end
