# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudsql < Formula
  desc "cloudsql"
  homepage "https://github.com/s-okayama/cloudsql"
  version "2.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s-okayama/cloudsql/releases/download/v2.2.1/cloudsql_2.2.1_Darwin_64bit.tar.gz"
      sha256 "300130f473b775421a3dd4f6007fc45645529d27585eb9ca6bd6e5e1ff737e32"

      define_method(:install) do
        bin.install "cloudsql"
        generate_completions_from_executable(bin/"cloudsql", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s-okayama/cloudsql/releases/download/v2.2.1/cloudsql_2.2.1_Darwin_ARM64.tar.gz"
      sha256 "3acb17703216f261468a58c3f7dcee734b402e3a3738d126dc8a052fa6f873df"

      define_method(:install) do
        bin.install "cloudsql"
        generate_completions_from_executable(bin/"cloudsql", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-okayama/cloudsql/releases/download/v2.2.1/cloudsql_2.2.1_Linux_64bit.tar.gz"
      sha256 "c4add5c08691fb5e40a3f901376a99a9594754d5bc2af1ab25ac17e2f1059a73"
      define_method(:install) do
        bin.install "cloudsql"
        generate_completions_from_executable(bin/"cloudsql", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-okayama/cloudsql/releases/download/v2.2.1/cloudsql_2.2.1_Linux_ARM64.tar.gz"
      sha256 "5314de7e7e1658d8f49a7b62c9b660303313e58a7f45a90d030bc7963405353a"
      define_method(:install) do
        bin.install "cloudsql"
        generate_completions_from_executable(bin/"cloudsql", "completion")
      end
    end
  end

  test do
    system "#{bin}/cloudsql --version"
  end
end
